services:
  - type: web
    name: esociety
    env: python
    buildCommand: pip install -r requirements.txt && python esociety/manage.py collectstatic --noinput && python esociety/manage.py migrate
    startCommand: gunicorn esociety.wsgi:application --chdir esociety
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
