# Generated by Django 6.0.2 on 2026-02-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.BigIntegerField(max_length=15, null=True),
        ),
    ]
