# Generated by Django 6.0.2 on 2026-03-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_mobile_number_remove_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(null=True),
        ),
    ]
