# Generated by Django 6.0.2 on 2026-03-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
