# Generated by Django 6.0.2 on 2026-03-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_demobooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inactive', 'Inactive'), ('active', 'Active'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], default='inactive', max_length=20),
        ),
    ]
