# Generated by Django 6.0.2 on 2026-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_alter_pollvote_voter_alter_poll_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='registered_by',
            field=models.CharField(choices=[('resident', 'Resident'), ('guard', 'Guard')], default='resident', max_length=20),
        ),
    ]
