# Generated by Django 6.0.2 on 2026-03-08 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_visitor_registered_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resident',
            field=models.ForeignKey(limit_choices_to={'role': 'Resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facilitybooking',
            name='booked_by',
            field=models.ForeignKey(limit_choices_to={'role': 'Resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='facility_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'Admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='resident',
            field=models.ForeignKey(limit_choices_to={'role': 'Resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'Admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='voter',
            field=models.ForeignKey(limit_choices_to={'role': 'Resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='guard',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Securityguard'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='registered_by',
            field=models.CharField(choices=[('resident', 'Resident'), ('Securityguard', 'Securityguard')], default='Resident', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='resident',
            field=models.ForeignKey(limit_choices_to={'role': 'Resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
