# Generated by Django 6.0.2 on 2026-03-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0004_alter_complaint_resident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_photos/'),
        ),
    ]
