# Generated by Django 6.0.2 on 2026-04-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0006_maintenanceconfig_maintenancedue'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitybooking',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_booking', to='society.payment'),
        ),
    ]
